language: python
python:
  - "3.6"
install:
  - pip install -r requirements.txt
  - pip install coveralls
script:
  # - nosetests --with-coverage
  - pytest --cov
  - coverage
  # - coverage3 report
  # - coveralls
# after_success:
#   - coveralls
#   - coverage
#   - coverage3 report
